packages:
  - "packages/*"
  - "apps/*"
  - "plugins/games/*"
  - "plugins/skins/*"
  - "plugins/tools/*"
  - "plugins/providers/*"
allowBuilds:
  '@google/genai': false
  '@swc/core': false
  esbuild: false
  protobufjs: false